route:
  receiver: 'Mail Alert'
  # group_by: [ alertname ]
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'Mail Alert'
    email_configs:
      - smarthost: 'smtp.pinter-net.at:587'
        auth_username: 'alert@pinter-net.at'
        auth_password: "Zuch4u3rFr4nkrchLsungen"
        from: 'alert@pinter-net.at'
        to: 'stefan@pinter-net.at'
        headers:
          subject: 'Prometheus Mail Alerts'
