version: '3.7'

volumes:
    prometheus_data: {}
    alertmanager_data: {}
    grafana_data: {}

networks:
  front-tier:
  back-tier:

services:

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
#      - pushgateway:pushgateway
    depends_on:
      - cadvisor
#      - pushgateway
    networks:
      - back-tier
    restart: always
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == ${HOSTNAME}

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - /portainer/prometheus/alertmanager/config.yml:/etc/alertmanager/config.yml
      - alertmanager_data:/alertmanager
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == ${HOSTNAME}
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always


#  pushgateway:
#    image: prom/pushgateway
#    restart: always
#    expose:
#      - 9091
#    ports:
#      - "9091:9091"
#    networks:
#      - back-tier

  pve-exporter:
    image: prompve/prometheus-pve-exporter:latest
    ports:
      - 9221:9221
    volumes: 
      - /portainer/prometheus/pve-exporter/pve.yml:/etc/prometheus/pve.yml
    restart: always
    networks:
      - back-tier

  idrac-exporter:
    image: mrlhansen/idrac_exporter
    ports: 
      - 9348:9348
    volumes:
      - /portainer/prometheus/idrac_exporter/idrac.yml:/etc/prometheus/idrac.yml
    restart: always
    networks:
      - back-tier

  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    command: --config.file=/config/blackbox.yml
    ports: 
      - 9115:9115
    volumes:
      - ./blackbox_exporter/blackbox.yml:/config/blackbox.yml
    extra_hosts:
      - "fw.pinter-net.at:192.168.10.254"
      - "cloud.pinter-net.at:80.109.218.159"
      - "hetzner01.pinter-net.at:116.203.206.46"
      - "imap.pinter-net.at:116.203.206.46"
      - "media.pinter-net.at:80.109.218.159"
      - "smtp.pinter-net.at:116.203.206.46"
      - "vpn.pinter-net.at:80.109.218.159"
      - "hv3.pinter-net.at:192.168.45.3"
      - "hv4.pinter-net.at:192.168.45.4"
      - "rpi-tv.pinter-net.at:192.168.10.21"
      - "rpi-piano.pinter-net.at:192.168.10.15"
      - "rpi-music.pinter-net.at:192.168.10.14"
      - "stefanpc.pinter-net.at:192.168.10.25"
      - "rpi-octoprint.pinter-net.at:192.168.10.13"
      - "drucker.pinter-net.at:192.168.10.200"
      - "dl.pinter-net.at:192.168.11.254"
      - "zentyal.pinter-net.at:192.168.11.254"
      - "hypervisor.pinter-net.at:192.168.11.254"
      - "print.pinter-net.at:192.168.11.254"
      - "nas.pinter-net.at:192.168.45.107"
      - "arcade.pinter-net.at:192.168.10.24"
      - "music.pinter-net.at:192.168.11.254"
      - "trans.pinter-net.at:192.168.11.254"
      - "portainer.pinter-net.at:192.168.11.254"
      - "pihole-pri.pinter-net.at:192.168.11.254"
      - "pihole-sec.pinter-net.at:192.168.11.254"
      - "grafana.pinter-net.at:192.168.11.254"
      - "prometheus.pinter-net.at:192.168.11.254"
      - "alertmanager.pinter-net.at:192.168.11.254"
      - "dck8.pinter-net.at:192.168.45.208"
      - "dck9.pinter-net.at:192.168.3.209"
      - "dck4.pinter-net.at:192.168.45.204"
      - "tdarr.pinter-net.at:192.168.11.254"
      - "omv.pinter-net.at:192.168.11.254"
      - "lxc3.pinter-net.at:192.168.3.103"
      - "photo.pinter-net.at:192.168.11.254"
    restart: always
    networks:
      - back-tier

#  snmp_exporter:
#    image: quay.io/prometheus/snmp-exporter
#    volumes:
#      - /opt/docker-persist/snmp-exporter:/etc/snmp_exporter
#    ports:
#      - 9116:9116
#      - 116:116/udp
#    restart: always
#    command: --config.file=/etc/snmp_exporter/snmp.yml
#    networks:
#      - back-tier
