global:
  scrape_interval:     75s # By default, scrape targets every 15 seconds.
  evaluation_interval: 75s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'pinter-net'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - '*.rules'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_config_files:
  - "scraper/*.yml"

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 75s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 75s
    static_configs:
      - targets: 
        - cadvisor:8080
        - 192.168.3.209:8081
        - 192.168.45.204:8080

  - job_name: 'node-exporter'
    scrape_interval: 75s
    static_configs:
      - targets:
        - node-exporter:9100
        - 192.168.45.254:9100
        - 192.168.45.204:9100
        - 192.168.45.208:9100
        - 192.168.45.3:9100
        - 192.168.45.4:9100
        - 192.168.45.5:9100
        - 192.168.45.107:9100
        - 192.168.3.209:9100
        - smtp.pinter-net.at:9100

  - job_name: 'hacluster-exporter'
    scrape_interval: 75s
    static_configs:
      - targets: ['192.168.45.3:9664', '192.168.45.4:9664']

  - job_name: 'pve'
    static_configs:
      - targets:
        - 192.168.45.3
        - 192.168.45.4
        - 192.168.45.5
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pve-exporter:9221  # PVE exporter.

  - job_name: 'idrac'
    scrape_interval: 15s
    static_configs:
      - targets:
        - 192.168.4.3
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: idrac-exporter:9348

  - job_name: 'HTTP Checks unsecure'
    metrics_path: /probe
    params:
      module: [http_2xx_get_unsecure]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://192.168.45.3:8006
        - https://192.168.45.4:8006
        - https://192.168.45.5:8006
        - https://192.168.45.254
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'HTTP Checks'
    metrics_path: /probe
    params:
      module: [http_2xx_get_secure]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://cloud.pinter-net.at
        - https://dl.pinter-net.at
        - https://smtp.pinter-net.at
        - https://hypervisor.pinter-net.at
        - https://portainer.pinter-net.at
        - https://pihole-pri.pinter-net.at/admin
        - https://pihole-sec.pinter-net.at/admin
        - https://grafana.pinter-net.at
        - https://prometheus.pinter-net.at
        - https://alertmanager.pinter-net.at
        - https://omv.pinter-net.at
        - https://photo.pinter-net.at
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.

  - job_name: SSH Checks
    scrape_timeout: 75s
    scrape_interval: 75s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
     - targets:
        - 192.168.45.3:22
        - 192.168.45.4:22
        - 192.168.45.5:22
        - 192.168.45.204:22
        - 192.168.45.208:22
        - 192.168.3.209:22
        - 192.168.3.103:22
        - 192.168.45.107:22
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: blackbox_exporter:9115
  
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['blackbox_exporter:9115']
