---
modules:
  default:
    headers:
      X-Dummy: my-test-header
    metrics:
    - name: example_global_value
      path: '{ .totalBalance }'
      help: Example of a top-level global value scrape in the json


# {"totalBalance":"5415986384","sigLockedBalance":"5041598656","ledgerIndex":9274289}
#
# curl -s "127.0.0.1:7979/probe?module=default&target=https://chronicle.stardust-mainnet.iotaledger.net/api/explorer/v2/balance/iota1qrx7ksnd0sftvczl4ctcrsg3vv4zvgvv7nrw8vq592m9ah3qaf4u2uja8l7"
#
# curl -L -X GET 'https://chronicle.stardust-mainnet.iotaledger.net/api/explorer/v2/balance/iota1qrx7ksnd0sftvczl4ctcrsg3vv4zvgvv7nrw8vq592m9ah3qaf4u2uja8l7' -H 'Accept: application/json'

  animals:
    metrics:
    - name: animal
      type: object
      help: Example of top-level lists in a separate module
      path: '{ [*] }'
      labels:
        name: '{ .noun }'
        predator: '{ .predator }'
      values:
        population: '{ .population }'

    ## HTTP connection configurations can be set in 'modules.<module_name>.http_client_config' field. For full http client config parameters, ref: https://pkg.go.dev/github.com/prometheus/common/config?tab=doc#HTTPClientConfig
    #
    # http_client_config:
    #   tls_config:
    #     insecure_skip_verify: true
    #   basic_auth:
    #     username: myuser
    #     #password: veryverysecret
    #     password_file: /tmp/mysecret.txt

    ## List of accepted status codes for this probe can be set in 'modules.<module_name>.valid_status_codes' field. Defaults to 2xx.
    # valid_status_codes: [ <int>, ... | default = 2xx ]

    ## If 'modueles.<module_name>.body' field is set, it will be sent by the exporter as the body content in the scrape request. The HTTP method will also be set as 'POST' in this case.
    # body:
    #   content: |
    #     {"time_diff": "1m25s", "anotherVar": "some value"}

    ## The body content can also be a Go Template (https://golang.org/pkg/text/template), with all the functions from the Sprig library (https://masterminds.github.io/sprig/) available. All the query parameters sent by prometheus in the scrape query to the exporter, are available in the template.
    # body:
    #   content: |
    #     {"time_diff": "{{ duration `95` }}","anotherVar": "{{ .myVal | first }}"}
    #   templatize: true

